name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/snapshot_sequencer_test'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE snapshot_sequencer_test;' -uroot -proot
          mysql -uroot -proot snapshot_sequencer_test < src/helpers/schema.sql
          mysql -uroot -proot snapshot_sequencer_test < test/schema.sql
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          mysql -uroot -proot -e "FLUSH PRIVILEGES;"
      - run: yarn install
      - run: yarn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
